### PR TITLE
Addition of Minutes from the 20150129 Advisory Board Meeting

### PR DESCRIPTION
**Pull request by totherik**

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
@totherik just out of curiosity: why does it take a month between the meeting and uploading the minutes?

**Comment by totherik** [comment]
Thanks for the question. In the past it typically hasn't take a month, so I apologize for the inconvenience this time.

After each meeting, participants review the notes for errors or ommissions. During that time period after the 1/29 meeting there was a lot of activity, including NodeSummit and the announcement of the foundation, during which time I merely forgot to follow up and submit the PR. I was reminded of that fact while preparing for this meeting and corrected the situation as quickly as possible.

This time around will be more timely, and again, I apologize for the inconvenience.

**Comment by yoshuawuyts** [comment]
@totherik no worries, I understand. Thanks for the quick reply!

**Comment by totherik** [comment]
Self-merging.

**Pull request merged**
